// Generated by CoffeeScript 1.10.0
(function() {
  var API, RootsUtil, W, _, add_posts_to_locals, add_urls_to_posts, async, get_posts_and_routes, path, render_single_views, request;

  API = require('./api');

  W = require('when');

  RootsUtil = require('roots-util');

  _ = require('lodash');

  path = require('path');

  async = require('async');

  module.exports = function(opts) {
    var RootsWordpress;
    if (opts == null) {
      opts = {};
    }
    if (!opts.site) {
      throw new Error('You must supply a site url or id');
    }
    if (!opts.post_types) {
      opts.post_types = {
        post: {}
      };
    }
    return RootsWordpress = (function() {
      function RootsWordpress(roots) {
        this.roots = roots;
        this.util = new RootsUtil(this.roots);
      }

      RootsWordpress.prototype.setup = function() {
        var all, base, config, type;
        if ((base = this.roots.config).locals == null) {
          base.locals = {};
        }
        this.roots.config.locals.wordpress = {};
        all = (function() {
          var ref, results;
          ref = opts.post_types;
          results = [];
          for (type in ref) {
            config = ref[type];
            results.push(request(opts.site, type, config).then(get_posts_and_routes.bind(this, type)).then(add_urls_to_posts).then(add_posts_to_locals.bind(this, type)).then(render_single_views.bind(this, config, type)));
          }
          return results;
        }).call(this);
        return W.all(all);
      };

      return RootsWordpress;

    })();
  };

  request = function(site, type, config) {
    var pathName;
    if (!config.route) {
      config.route = "posts";
    }
    pathName = site + config.route;
    return API({
      path: pathName,
      params: config.apiParams
    });
  };

  get_posts_and_routes = function(type, res) {
    var posts;
    posts = res.entity;
    if (type === "categories") {
      return {
        urls: [],
        posts: posts
      };
    }
    return W.map(posts, (function(_this) {
      return function(p) {
        var output;
        output = "/" + type + "/" + p.slug + ".html";
        return output;
      };
    })(this)).then(function(urls) {
      return {
        urls: urls,
        posts: posts
      };
    });
  };

  render_single_views = function(config, type, posts) {
    if (!config.template) {
      return posts;
    }
    return async.eachSeries(posts, (function(_this) {
      return function(post, callback) {
        var compiler, locals, output, tpl;
        tpl = path.join(_this.roots.root, config.template);
        locals = _this.roots.config.locals;
        locals.post = post;
        output = type + "/" + post.slug + ".html";
        compiler = _.find(_this.roots.config.compilers, function(c) {
          return _.contains(c.extensions, path.extname(tpl).substring(1));
        });
        return compiler.renderFile(tpl, locals).then(function(res) {
          return _this.util.write(output, res.result);
        }).then(function() {
          return callback(null);
        });
      };
    })(this));
  };

  add_urls_to_posts = function(obj) {
    return obj.posts.map(function(post, i) {
      post._url = obj.urls[i];
      return post;
    });
  };

  add_posts_to_locals = function(type, posts) {
    return this.roots.config.locals.wordpress[type] = posts;
  };

}).call(this);
